config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "homes/about"=>"homes#about", as: 'about'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # deviseに新しくルーティングを追加
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get :favorites
    end
  end

  resources :posts, only: [:index,:create,:show, :edit, :destroy, :update] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  
  resources :chats, only: [:show, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @post = Post.find(params[:post_id])
    @post_comment = PostComment.new(post_comment_params)
    @post_comment.post_id = @post.id
    @post_comment.user_id = current_user.id
    @post_comment.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    post_comment = @post.post_comments.find(params[:id])
    post_comment.destroy
  end


  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_error.js.erb
$(".body > .container").prepend("<%= j(render 'layouts/errors', obj: @post_comment) %>");

app/views/post_comments/_form.html.erb
 <div class="new-comment">
  <%= form_with model: [post, post_comment], local: false do |f| %>
    <!--エラーメッセージ-->
    <%= render 'layouts/errors', obj: f.object %>
    <%= f.text_area :comment, rows: '5', placeholder: " コメントを入力", class: "w-100" %>
    <%= f.submit "Post Comment", class: 'btn btn-secondary' %>
  <% end %>
</div>

app/views/post_comments/_index.html.erb
<thead>
  <th></th>
  <th class="text-center">Users Comments</th>
  <th colspan="3"></th>
</thead>
<tbody>
<% post.post_comments.each do |post_comment| %>
  <% post_comment_user = post_comment.user %>
  <tr>
    <td>
      <%= link_to user_path(post_comment.user), class: "user_#{post_comment_user.id}" do %>
        <%= image_tag post_comment.user.get_profile_image, size:"80x80", class: 'img-thumbnail' %></br>
        <i class="fas fa-user"></i> <%= post_comment.user.name %>
      <% end %>
    </td>
    <td><%= post_comment.comment %></td>
    <% if post_comment.user == current_user %>
      <td><%= link_to "Destroy", post_post_comment_path(post_comment.post_id, post_comment.id), method: :delete, remote: true, data: { confirm: '本当に削除しますか？'}, class: 'btn btn-danger' %></td>
    <% end %>
  </tr>
<% end %>
</tbody>

app/views/post_comments/create.js.erb
$("#post_<%= @post.id %> .comments-count").html("コメント数: <%= @post.post_comments.count %>");
$(".post_comments").html("<%= j(render 'post_comments/index', post: @post) %>");
$("#post_comment_comment").val("");

app/views/post_comments/destroy.js.erb
$("#post_<%= @post.id %> .comments-count").html("コメント数: <%= @post.post_comments.count %>");
$(".post_comments").html("<%= j(render 'post_comments/index', post: @post) %>");
$("#post_comment_comment").val("");

app/views/post_comments/post_comments.js.erb
<!--id="comments_areaにrenderで指定した部分テンプレートに更新-->
$("#comments_area").html("<%= j(render 'post_comments/index', post: @post, post_comments: @post_comments) %>");
<!--フォームを送信したあとにフォームの値を空にする-->
$("text_area").val('');