config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "homes/about"=>"homes#about", as: 'about'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # deviseに新しくルーティングを追加
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get :favorites
    end
  end

  resources :posts, only: [:index,:create,:show, :edit, :destroy, :update] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  
  resources :chats, only: [:show, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length:{maximum:200}

  has_one_attached :image

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @post = Post.new
    # 検索用の記述
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:user).page(params[:page]).order("created_at desc")
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post.id), notice: "You have created post successfully."
    else
      @posts = Post.all
      render 'index'
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @post_new = Post.new
    @post_comment = PostComment.new
  end


  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "You have updated post successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end


  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

  def ensure_correct_user
    @post = Post.find(params[:id])
    @user = @post.user
    unless @user == current_user
      redirect_to post_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model:post, local:true do |f| %>
<%= render 'layouts/errors', obj: f.object %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control post_title' %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :body, class: 'form-control post_body' %>
  </div>
  <div class="form-group">
    <%= f.file_field :image, class: 'post_image', accept: 'image/*' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/posts/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% posts.each do |post| %>
      <tr id="post_<%= post.id %>">
        <td>
          <%= link_to user_path(post.user) do %>
            <%= image_tag post.user.get_profile_image, size:'100x100', class: 'img-thumbnail' %></br>
            <i class="fas fa-user"></i> <%= post.user.name %>
          <% end %>
        </td>
        <td><%= link_to post.title, post_path(post.id) %></td>
        <td><%= post.body %></td>
        <td>
          <% if post.image.attached? %>
            <%= link_to post_path(post.id) do %>
              <%= image_tag post.image, size:'140x140' %>
            <% end %>
          <% end %>
        </td>
        <!--いいね部分-->
        <td id="favorite_buttons_<%= post.id %>">
          <%= render "favorites/favorite-btn", post: post %>
        </td>
        <!--コメント数表示-->
        <td>
          <% unless post.post_comments.count == 0 %>
            <%= link_to post_path(post.id) do %>
              <i class="fas fa-comments"></i><%= post.post_comments.count %>
            <% end %>
          <% else %>
            <%= link_to post_path(post.id) do %>
              <i class="far fa-comments"></i> 0
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/_search.html.erb
<div class="d-flex justify-content-center mt-1 mb-3">
  <%= search_form_for @q, url: url do |f| %>
    <%= f.search_field :title_or_body_cont, class: 'pt-1 pb-1', placeholder: "検索ワード" %>
    <%= f.submit '投稿を検索', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Post</h1>
  		<%= render 'form', post: @post %>
  		<%= link_to 'Back', post_path(@post), class: "back" %>
  </div>
</div>

app/views/posts/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New Post</h2>
      <%= render 'form', post: @post %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <!--検索フォーム-->
      <%= render 'search', q: @q, url: posts_path %>
      <h2>Posts</h2>
      <%= render 'index', posts: @posts %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New Post</h2>
      <%= render 'form', post: @post_new %>
    </div>

    <div class='col-md-8 offset-md-1'>
  		<h2>Post detail</h2>
  		<table class='table'>
  		  <tr id="post_<%= @post.id %>">
          <td>
            <%= link_to user_path(@post.user) do %>
              <%= image_tag @post.user.get_profile_image, size:"100x100", class: 'img-thumbnail' %><br>
              <i class="fas fa-user"></i> <%= @post.user.name %>
            <% end %>
          </td>
          <td><%= link_to @post.title, post_path(@post) %></td>
          <td><%= @post.body %></td>
          <!--いいね機能-->
          <td id="favorite_buttons_<%= @post.id %>">
            <%= render "favorites/favorite-btn", post: @post %>
          </td>
          <% if @user == current_user %>
            <td><%= link_to 'Edit', edit_post_path(@post), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', post_path(@post), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>
      <!--投稿画像-->
      <div class="mb-3 px-3">
        <% if @post.image.attached? %>
          <%= link_to post_path(@post.id) do %>
            <%= image_tag @post.image, size:'500x400', class: 'w-100' %>
          <% end %>
        <% end %>
      </div>
      <!--コメント一覧-->
      <table class="post_comments table">
        <%= render 'post_comments/index', post: @post %>
      </table>
      <!--コメントフォーム-->
      <div id="comments_area">
        <%= render 'post_comments/form', post: @post, post_comment: @post_comment %>
      </div>
    </div>
  </div>
</div>